permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Nemo
  email: NemoTec@163.com
  link: http://xxxxx
  github: https://github.com/NemoTec

# 站点信息
title: Nemo
description: Meet my best!
url: http://xxxxx
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/nemo_logo.png
favicon: /public/img/nemo_logo.png

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: painterlin.com

# disqus 设置
disqus:
  shortname: Nemo

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
